# Generated by Django 5.0.3 on 2024-06-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lanzamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora', models.CharField(max_length=100, verbose_name='Operadora')),
                ('pais', models.CharField(max_length=40, verbose_name='País')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.BooleanField(default=False)),
                ('mcc', models.CharField(max_length=3, verbose_name='MCC')),
                ('mnc', models.CharField(max_length=3, verbose_name='MNC')),
                ('nc', models.CharField(max_length=3, verbose_name='NC')),
                ('cc', models.CharField(max_length=3, verbose_name='NC')),
                ('dmrt', models.CharField(max_length=4, verbose_name='DMRT')),
                ('carrier', models.CharField(choices=[('1', 'Syniverse'), ('2', 'Comfone')], max_length=1, verbose_name='Carrier')),
                ('ir21', models.ImageField(blank=True, null=True, upload_to='lanzamientos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lanzamiento',
                'verbose_name_plural': 'Lanzamientos',
            },
        ),
    ]
