# Generated by Django 5.0.3 on 2024-06-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanzamientos', '0002_lanzamiento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanzamiento',
            name='cc',
            field=models.CharField(max_length=3, verbose_name='CC'),
        ),
    ]
