# Generated by Django 5.0.3 on 2024-06-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanzamientos', '0003_alter_lanzamiento_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanzamiento',
            name='ir21',
            field=models.FileField(blank=True, null=True, upload_to='lanzamientos'),
        ),
    ]
