# Generated by Django 5.0.3 on 2024-06-16 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_sitio_central', models.BooleanField(verbose_name='Con sitio central')),
                ('vpn_instance', models.CharField(max_length=20, verbose_name='VPN instance')),
                ('tinco_movil', models.CharField(max_length=10, verbose_name='Tinco movil')),
                ('route_distinguisher', models.CharField(max_length=8, verbose_name='Route distinguisher')),
                ('vprn_id', models.CharField(max_length=8, verbose_name='VPRN Id')),
                ('red_mag', models.CharField(max_length=15, verbose_name='Red MAG')),
                ('conectividad_entre_moviles', models.CharField(choices=[('1', 'Full mesh'), ('2', 'Hub & spoke')], max_length=1, verbose_name='Conectividad entre moviles')),
                ('nombre_pool', models.CharField(max_length=15, verbose_name='Nombre del pool')),
                ('server_ip', models.CharField(max_length=15, verbose_name='Server IP')),
                ('wildcard', models.CharField(max_length=15, verbose_name='Wildcard')),
                ('acl_node', models.CharField(max_length=15, verbose_name='ACL Node')),
                ('nombre_acl', models.CharField(max_length=30, verbose_name='Nombre ACL')),
                ('prioridad', models.IntegerField(verbose_name='Prioridad')),
                ('nombre_pool_moviles', models.CharField(max_length=15, verbose_name='Nombre del pool moviles')),
                ('tipo_ip', models.CharField(choices=[('1', 'Fijas'), ('2', 'Dinamicas')], max_length=1, verbose_name='Tipo de IPs')),
                ('rango_ip_mag', models.CharField(max_length=15, verbose_name='Rango IP MAG')),
                ('rango_ip_mun', models.CharField(max_length=15, verbose_name='Rango IP MUN')),
                ('roaming', models.BooleanField()),
                ('apn', models.CharField(max_length=15, verbose_name='APN')),
                ('dns_1', models.CharField(max_length=15, verbose_name='DNS 1')),
                ('dns_2', models.CharField(max_length=15, verbose_name='DNS 2')),
                ('cliente_acm', models.CharField(max_length=15, verbose_name='Cliente ACM')),
                ('apn_id', models.IntegerField(unique=True, verbose_name='APN ID')),
                ('tinco_fija', models.CharField(max_length=15, verbose_name='TINCO fija')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('ip_router', models.CharField(max_length=15, verbose_name='IP Router')),
                ('contacto', models.CharField(max_length=200, verbose_name='Contacto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VPN',
                'verbose_name_plural': 'VPNs',
                'ordering': ['-created'],
            },
        ),
    ]
