# Generated by Django 5.0.3 on 2024-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_alter_vpn_acl_node_alter_vpn_apn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpn',
            name='tipo_ip',
        ),
        migrations.AlterField(
            model_name='vpn',
            name='apn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='APN'),
        ),
    ]
